# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Any-Renderer
version:      1.014
version_from: lib/Any/Renderer.pm
installdirs:  site
requires:
    File::Find:                    0
    File::Spec:                    0
    Log::Trace:                    0
    Test::Assertions:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
